[package]
name = "retag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.27", features = ["derive"] }
directories = "6.0.0"
ignore = "0.4.23"
rusqlite = { version = "0.33.0", features = ["bundled"] }
tempfile = "3.15.0"
